### ISSUE TITLE
[Possible Bug] No http camera IP's are displaying anything

### ISSUE THREAD

**Issue by RemakingEden** [woj-ciech/kamerka#14]
Hi,

Thanks for the tool, it is very interesting!

I'm unsure if this is a bug or I'm misunderstanding the use of this application. I thought some of the cameras would be accessible by a http dashboard. Not necessarily unprotected but contactable in some way. I have not found 1 out of the 30 or so I have tried.

Is this usual?

Are the searches via Shodan looking at active cameras or are they old records?

Here is an example of a search that showed many cameras but none were accessible.
python kamerka.py --lat 53.477059 --lon -2.239618 --camera 

Thank you!

**Comment by woj-ciech** [comment]
Hey,
Results are parsed from Shodan API, so it may happen that some cameras are no longer accessible. Also, not every camera runs on port 80, I recommend first to check it in details on shodan.io.
Remember that green icon means that response is 200 OK.

**Comment by RemakingEden** [comment]
I see, okay thanks. I will look into it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
