### ISSUE TITLE
Instagram locations

### ISSUE THREAD

**Issue by lorenzoromani1983** [woj-ciech/kamerka#15]
Hi.
Even if I added the additional method to InstagramAPI.py, I still get this message:

----------------Instagram----------------
Request return 429 error!
{u'status': u'fail', u'message': u'Please wait a few minutes before you try again.'}
Request return 404 error!
Login success!

Add additional method to Instagram library

what's wrong?
Is --instagram supposed to download POSTS or LOCATIONS from Instagram? As far as i Know, it is not possible to download posts from Instagram.

**Comment by woj-ciech** [comment]
Hey,
First, don't care about 'debug' information, it couldn't turn if off. Check exactly method's name it's  _geosearchLocation_ in the[ pull request](https://github.com/LevPasha/Instagram-API-python/pull/492/commits/ed74ee45fb3e3abe6df7f767d3353de6fd897401) is _geosearchLocations_ . Also, be sure that you paste it in right location, among other methods. 

It downloads nothing, first it checks for venues nearby your location and then passes it to get photos from this particular place.

**Comment by lorenzoromani1983** [comment]
sorry...i am not getting it. Still same error (only on Kali. On Windows it's ok).

**Comment by woj-ciech** [comment]
I was testing it on Kali as well, maybe try to remove try - except block on line [128](https://github.com/woj-ciech/kamerka/blob/master/kamerka.py#L128) and then check if issue persist and what is the exception.

**Comment by y0d4a** [comment]
hi, can you be more specific what need to change to work instagram?

tnx.

**Comment by woj-ciech** [comment]
Hey @y0d4a,
@lorenzoromani1983 has a problem with Instagram module so I advised to comment/delete try-except statements on line 128 and 130 and then check what exception appears. I suppose that you pasted method in wrong place. It should be in InstagramAPI.py file of the InstagramAPI framework, i.e. [here](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/InstagramAPI.py)

**Comment by y0d4a** [comment]
hi woj-ciech :) thank you for answer!
i try to comment 128+130, add new api script, add diff, but nothing...
This is output with commented those lines and added new API script with diff change:

> $ python2.7 kamerka.py --lat "44.8178131" --lon "20.4568974" --dark --twitter --camera --printer --flickr --instagram
Traceback (most recent call last):
  File "kamerka.py", line 16, in <module>
    from InstagramAPI import InstagramAPI
  File "/usr/local/lib/python2.7/dist-packages/InstagramAPI/__init__.py", line 1, in <module>
    ﻿from .InstagramAPI import *
  File "/usr/local/lib/python2.7/dist-packages/InstagramAPI/InstagramAPI.py", line 738
    def geosearchLocations(self, lat, lng):
                                          ^
IndentationError: unindent does not match any outer indentation level

**Comment by woj-ciech** [comment]
The error means that code was badly formatted, you forgot about indent. Anyway, I doubt that it would help. What I suggest is to take a look again what and where you pasted _geosearchLocation_ method. I can't replicate your issue
