### ISSUE TITLE
Icons Not Displayed on Map

### ISSUE THREAD

**Issue by alfakher1** [woj-ciech/kamerka#23]
Hi,
Enjoying the tools.Great Work.

 When I run the script I get results returned in the terminal, the map is created but I get no icons with one exception when I run python kamerka.py --country UK I see icons.

The only API I don't have is instagram.

Thanks in advance for your help/guidance.

**Comment by alfakher1** [comment]
FYI Copied from terminal

`1 page
Found tweet: -6.26319,53.34279
2 page
Found photo: -6.2732956,53.3493463
Found tweet: -6.27311,53.35851
3 page
Found tweet: -6.25784131,53.34415033
Found tweet: -6.28555298,53.34326268
Found tweet: -6.25145,53.34124
Found tweet: -6.2597,53.3478
4 page
5 page
`

`----------------Shodan camera----------------
Found 100 results
IP: 52.209.187.134
Coordinates: 53.3331,-6.248899999999992
IP: 93.107.239.145
Coordinates: 53.3331,-6.248899999999992
IP: 86.43.106.247
Coordinates: 53.34719999999999,-6.2438999999999965
IP: 86.43.64.125
Coordinates: 53.3331,-6.248899999999992
IP: 18.202.115.46
`

**Comment by woj-ciech** [comment]
Hey,
Can you please paste the exception you mentioned? It will be easier to detect what's wrong
