### ISSUE TITLE
I cant install kamerka, please check me

### ISSUE THREAD

**Issue by eticzone** [woj-ciech/kamerka#25]
I try but I get an error

**Comment by woj-ciech** [comment]
What kind of error? Please post stack trace or something.

**Comment by eticzone** [comment]
I activated my account, but it gives me the error

python kamerka.py --country IL
Fail to import moviepy. Need only for Video upload.
----------------Shodan ics----------------
Invalid API key
----------------Shodan ics----------------
Invalid API key
----------------Shodan ics----------------
Invalid API key
----------------Shodan ics----------------
Invalid API key
----------------Shodan ics----------------
Invalid API key
----------------Shodan ics----------------
Invalid API key
----------------Shodan ics----------------
Invalid API key
----------------Shodan ics----------------
Invalid API key
----------------Shodan ics----------------
Invalid API key
----------------Shodan ics----------------
Invalid API key
Saving map as IL.html

**Comment by eticzone** [comment]
("Twitter sent status 400 for URL: 1.1/search/tweets.json using parameters: (count=100&geocode=37.235%2C115.811111%2C3km&include_entities=True&max_id=None&oauth_consumer_key=&oauth_nonce=183030130039296484&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1563870954&oauth_version=1.0&q=%2A&result_type=mixed&oauth_signature=LZ7jfpRCDtrArJ%2F0d5HyPTvJ4AA%3D)\ndetails: {u'errors': [{u'message': u'Bad Authentication data.', u'code': 215}]}",)
----------------Shodan camera----------------
Nothing was found
----------------Shodan printer----------------
Nothing was found

**Comment by eticzone** [comment]
python kamerka.py --lat 37.8368723 --lon -122.2645793 --camera --flickr --instagram --twitter --printer --first 1 --last 1
Fail to import moviepy. Need only for Video upload.
usage: kamerka.py [-h] [--lat LAT] [--lon LON] [--radius RADIUS] [--dark]
                  [--twitter] [--camera] [--flickr] [--instagram] [--printer]
                  [--country COUNTRY]
kamerka.py: error: unrecognized arguments: --first 1 --last 1

**Comment by eticzone** [comment]
Traceback (most recent call last):
  File "kamerka.py", line 581, in <module>
    flickr_results = flickr_query(lat, lon)
  File "kamerka.py", line 263, in flickr_query
    print(Fore.RED +  e.args + Fore.RESET)
TypeError: cannot concatenate 'str' and 'tuple' objects

**Comment by eticzone** [comment]
--Instagram 

Request return 400 error!
{u'status': u'fail', u'message': u'Invalid Parameters', u'error_type': u'missing_parameters'}
Invalid Parameters
Saving map as 37.225,115.811111.html

**Comment by woj-ciech** [comment]
First one is about wrong API keys, from returned json - "'Bad Authentication data.', u'code': 215" (https://stackoverflow.com/questions/17143985/twitter-api-error-215) you have to paste your consumer key & secret and access key & secret. I have no problem with Twitter.
I've made small fixes for flickr --> https://github.com/woj-ciech/kamerka/commit/37b3b6554f6c15de3db135d2f7e791996d506b19  but unfortunately Instagram API is obsolete and it's not supported anymore. I will try to investigate it deeper when I find more time.

**Comment by eticzone** [comment]
python kamerka.py --country IL
Fail to import moviepy. Need only for Video upload.
Traceback (most recent call last):
  File "kamerka.py", line 858, in <module>
    shodan_ics_results = shodan_query(ics_query+country, "ics")
TypeError: shodan_query() takes exactly 3 arguments (2 given)

**Comment by woj-ciech** [comment]
Should be fine now. 
https://github.com/woj-ciech/kamerka/commit/37b3b6554f6c15de3db135d2f7e791996d506b19
