### ISSUE TITLE
Does not work with free shodan.io API plan

### ISSUE THREAD

**Issue by mweinelt** [woj-ciech/kamerka#3]
The script silently exits when the API key uses the free tier.

This can be seen if you print the exception instead of `e.message` in `shodan_query()`

> Please upgrade your API plan to use filters or paging.

Please add this information to the README

**Comment by woj-ciech** [comment]
Thanks, I didn't notice that.

**Comment by blcarson** [comment]
Their cheapest plan is $60/mo. Is there a similar service we can use that's any cheaper?

**Comment by achillean** [comment]
@blcarson The cheapest plan is the Shodan Membership which is a one-time payment of $49:

https://www.shodan.io/store/member

**Comment by luixal** [comment]
Indeed. I know it's on the readme, on the restrictions plan but... i still wasted some time because I didn't notice it... should be bold and bigger or something to catch eye at first glance.
