### ISSUE TITLE
pip command syntax is incorrect

### ISSUE THREAD

**Issue by pdurusau** [woj-ciech/kamerka#4]
Reads: pip -r install requirements

Should read: pip install -r requirements.txt

**Comment by tchaguitos** [comment]
@pdurusau https://github.com/woj-ciech/kamerka/pull/6

**Comment by DeanForde** [comment]
receiving error when executing the command  pip install -r requirements.txt, error message received is as follows "Could not find a version that satisfies the requirement requirements (from versions: )
No matching distribution found for requirements "

**Comment by tchaguitos** [comment]
@DeanForde change your requirements.txt to this and try again, please

`
colorama==0.3.9
`
`
folium==0.6.0
`
`
geopy==1.17.0
`
`
shodan==1.10.4
`
`
geographiclib==1.46.3
`
